from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 588)
        MainWindow.setMinimumSize(QtCore.QSize(361, 588))
        MainWindow.setMaximumSize(QtCore.QSize(361, 588))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 341, 135))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputLabel.sizePolicy().hasHeightForWidth())
        self.outputLabel.setSizePolicy(sizePolicy)
        self.outputLabel.setMaximumSize(QtCore.QSize(361, 588))
        self.outputLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outputLabel.setLineWidth(2)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 180, 321, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.esittir = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.hesapla())
        self.esittir.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esittir.sizePolicy().hasHeightForWidth())
        self.esittir.setSizePolicy(sizePolicy)
        self.esittir.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.esittir.setFont(font)
        self.esittir.setObjectName("esittir")
        self.gridLayout.addWidget(self.esittir, 0, 0, 1, 1)
        self.sifirla = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.outputLabel.setText("0"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sifirla.sizePolicy().hasHeightForWidth())
        self.sifirla.setSizePolicy(sizePolicy)
        self.sifirla.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sifirla.setFont(font)
        self.sifirla.setObjectName("sifirla")
        self.gridLayout.addWidget(self.sifirla, 0, 1, 1, 1)
        self.sifir = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("0"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sifir.sizePolicy().hasHeightForWidth())
        self.sifir.setSizePolicy(sizePolicy)
        self.sifir.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sifir.setFont(font)
        self.sifir.setObjectName("sifir")
        self.gridLayout.addWidget(self.sifir, 0, 2, 1, 1)
        self.bolu = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("/"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bolu.sizePolicy().hasHeightForWidth())
        self.bolu.setSizePolicy(sizePolicy)
        self.bolu.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bolu.setFont(font)
        self.bolu.setObjectName("bolu")
        self.gridLayout.addWidget(self.bolu, 0, 3, 1, 1)
        self.yedi = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("7"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yedi.sizePolicy().hasHeightForWidth())
        self.yedi.setSizePolicy(sizePolicy)
        self.yedi.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yedi.setFont(font)
        self.yedi.setObjectName("yedi")
        self.gridLayout.addWidget(self.yedi, 1, 0, 1, 1)
        self.sekiz = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("8"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sekiz.sizePolicy().hasHeightForWidth())
        self.sekiz.setSizePolicy(sizePolicy)
        self.sekiz.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sekiz.setFont(font)
        self.sekiz.setObjectName("sekiz")
        self.gridLayout.addWidget(self.sekiz, 1, 1, 1, 1)
        self.dokuz = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("9"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dokuz.sizePolicy().hasHeightForWidth())
        self.dokuz.setSizePolicy(sizePolicy)
        self.dokuz.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dokuz.setFont(font)
        self.dokuz.setObjectName("dokuz")
        self.gridLayout.addWidget(self.dokuz, 1, 2, 1, 1)
        self.carpi = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("*"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carpi.sizePolicy().hasHeightForWidth())
        self.carpi.setSizePolicy(sizePolicy)
        self.carpi.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.carpi.setFont(font)
        self.carpi.setObjectName("carpi")
        self.gridLayout.addWidget(self.carpi, 1, 3, 1, 1)
        self.dort = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("4"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dort.sizePolicy().hasHeightForWidth())
        self.dort.setSizePolicy(sizePolicy)
        self.dort.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dort.setFont(font)
        self.dort.setObjectName("dort")
        self.gridLayout.addWidget(self.dort, 2, 0, 1, 1)
        self.bes = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("5"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bes.sizePolicy().hasHeightForWidth())
        self.bes.setSizePolicy(sizePolicy)
        self.bes.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bes.setFont(font)
        self.bes.setObjectName("bes")
        self.gridLayout.addWidget(self.bes, 2, 1, 1, 1)
        self.alti = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("6"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alti.sizePolicy().hasHeightForWidth())
        self.alti.setSizePolicy(sizePolicy)
        self.alti.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.alti.setFont(font)
        self.alti.setObjectName("alti")
        self.gridLayout.addWidget(self.alti, 2, 2, 1, 1)
        self.eksi = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("-"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eksi.sizePolicy().hasHeightForWidth())
        self.eksi.setSizePolicy(sizePolicy)
        self.eksi.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.eksi.setFont(font)
        self.eksi.setObjectName("eksi")
        self.gridLayout.addWidget(self.eksi, 2, 3, 1, 1)
        self.bir = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("1"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bir.sizePolicy().hasHeightForWidth())
        self.bir.setSizePolicy(sizePolicy)
        self.bir.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bir.setFont(font)
        self.bir.setObjectName("bir")
        self.gridLayout.addWidget(self.bir, 3, 0, 1, 1)
        self.iki = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("2"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iki.sizePolicy().hasHeightForWidth())
        self.iki.setSizePolicy(sizePolicy)
        self.iki.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.iki.setFont(font)
        self.iki.setObjectName("iki")
        self.gridLayout.addWidget(self.iki, 3, 1, 1, 1)
        self.uc = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("3"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uc.sizePolicy().hasHeightForWidth())
        self.uc.setSizePolicy(sizePolicy)
        self.uc.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.uc.setFont(font)
        self.uc.setObjectName("uc")
        self.gridLayout.addWidget(self.uc, 3, 2, 1, 1)
        self.arti = QtWidgets.QPushButton(self.layoutWidget, clicked=lambda: self.press_it("+"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arti.sizePolicy().hasHeightForWidth())
        self.arti.setSizePolicy(sizePolicy)
        self.arti.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.arti.setFont(font)
        self.arti.setObjectName("arti")
        self.gridLayout.addWidget(self.arti, 3, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def press_it(self, pressed):
        if pressed == "C":
            self.outputLabel.setText("0")
        else:
            if self.outputLabel.text() == "0":
                self.outputLabel.setText("")
            self.outputLabel.setText(f'{self.outputLabel.text()}{pressed}')

    def kaldir(self):
        ekran = self.outputLabel.text()
        ekran = ekran[:-1]
        self.outputLabel.setText(ekran)

    # Hesaplamalar
    def hesapla(self):
        ekran = self.outputLabel.text()
        try:
            sonuc = eval(ekran)  #'evaluate' kısaltması
            self.outputLabel.setText(str(sonuc))
        except:
            self.outputLabel.setText("HATA")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hesap Makinesi 1.0"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.esittir.setText(_translate("MainWindow", "="))
        self.sifirla.setText(_translate("MainWindow", "C"))
        self.sifir.setText(_translate("MainWindow", "0"))
        self.bolu.setText(_translate("MainWindow", "/"))
        self.yedi.setText(_translate("MainWindow", "7"))
        self.sekiz.setText(_translate("MainWindow", "8"))
        self.dokuz.setText(_translate("MainWindow", "9"))
        self.carpi.setText(_translate("MainWindow", "x"))
        self.dort.setText(_translate("MainWindow", "4"))
        self.bes.setText(_translate("MainWindow", "5"))
        self.alti.setText(_translate("MainWindow", "6"))
        self.eksi.setText(_translate("MainWindow", "-"))
        self.bir.setText(_translate("MainWindow", "1"))
        self.iki.setText(_translate("MainWindow", "2"))
        self.uc.setText(_translate("MainWindow", "3"))
        self.arti.setText(_translate("MainWindow", "+"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())