from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 588)
        MainWindow.setMinimumSize(QtCore.QSize(361, 588))
        MainWindow.setMaximumSize(QtCore.QSize(361, 588))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.arti = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("+"))
        self.arti.setGeometry(QtCore.QRect(262, 440, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arti.sizePolicy().hasHeightForWidth())
        self.arti.setSizePolicy(sizePolicy)
        self.arti.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.arti.setFont(font)
        self.arti.setObjectName("arti")
        self.carpi = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("*"))
        self.carpi.setGeometry(QtCore.QRect(262, 280, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carpi.sizePolicy().hasHeightForWidth())
        self.carpi.setSizePolicy(sizePolicy)
        self.carpi.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.carpi.setFont(font)
        self.carpi.setObjectName("carpi")
        self.yedi = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("7"))
        self.yedi.setGeometry(QtCore.QRect(34, 280, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yedi.sizePolicy().hasHeightForWidth())
        self.yedi.setSizePolicy(sizePolicy)
        self.yedi.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yedi.setFont(font)
        self.yedi.setObjectName("yedi")
        self.dokuz = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("9"))
        self.dokuz.setGeometry(QtCore.QRect(186, 280, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dokuz.sizePolicy().hasHeightForWidth())
        self.dokuz.setSizePolicy(sizePolicy)
        self.dokuz.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dokuz.setFont(font)
        self.dokuz.setObjectName("dokuz")
        self.bolu = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("/"))
        self.bolu.setGeometry(QtCore.QRect(262, 200, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bolu.sizePolicy().hasHeightForWidth())
        self.bolu.setSizePolicy(sizePolicy)
        self.bolu.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bolu.setFont(font)
        self.bolu.setObjectName("bolu")
        self.sil = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("0"))
        self.sil.setGeometry(QtCore.QRect(186, 200, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sil.sizePolicy().hasHeightForWidth())
        self.sil.setSizePolicy(sizePolicy)
        self.sil.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sil.setFont(font)
        self.sil.setObjectName("sil")
        self.dort = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("4"))
        self.dort.setGeometry(QtCore.QRect(34, 360, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dort.sizePolicy().hasHeightForWidth())
        self.dort.setSizePolicy(sizePolicy)
        self.dort.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dort.setFont(font)
        self.dort.setObjectName("dort")
        self.bir = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("1"))
        self.bir.setGeometry(QtCore.QRect(34, 440, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bir.sizePolicy().hasHeightForWidth())
        self.bir.setSizePolicy(sizePolicy)
        self.bir.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bir.setFont(font)
        self.bir.setObjectName("bir")
        self.alti = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("6"))
        self.alti.setGeometry(QtCore.QRect(186, 360, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alti.sizePolicy().hasHeightForWidth())
        self.alti.setSizePolicy(sizePolicy)
        self.alti.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.alti.setFont(font)
        self.alti.setObjectName("alti")
        self.uc = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("3"))
        self.uc.setGeometry(QtCore.QRect(186, 440, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uc.sizePolicy().hasHeightForWidth())
        self.uc.setSizePolicy(sizePolicy)
        self.uc.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.uc.setFont(font)
        self.uc.setObjectName("uc")
        self.sekiz = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("8"))
        self.sekiz.setGeometry(QtCore.QRect(110, 280, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sekiz.sizePolicy().hasHeightForWidth())
        self.sekiz.setSizePolicy(sizePolicy)
        self.sekiz.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sekiz.setFont(font)
        self.sekiz.setObjectName("sekiz")
        self.bes = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("5"))
        self.bes.setGeometry(QtCore.QRect(110, 360, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bes.sizePolicy().hasHeightForWidth())
        self.bes.setSizePolicy(sizePolicy)
        self.bes.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bes.setFont(font)
        self.bes.setObjectName("bes")
        self.iki = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("2"))
        self.iki.setGeometry(QtCore.QRect(110, 440, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iki.sizePolicy().hasHeightForWidth())
        self.iki.setSizePolicy(sizePolicy)
        self.iki.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.iki.setFont(font)
        self.iki.setObjectName("iki")
        self.sifirla = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.outputLabel.setText("0"))
        self.sifirla.setGeometry(QtCore.QRect(110, 200, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sifirla.sizePolicy().hasHeightForWidth())
        self.sifirla.setSizePolicy(sizePolicy)
        self.sifirla.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sifirla.setFont(font)
        self.sifirla.setObjectName("sifirla")
        self.eksi = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("-"))
        self.eksi.setGeometry(QtCore.QRect(262, 360, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eksi.sizePolicy().hasHeightForWidth())
        self.eksi.setSizePolicy(sizePolicy)
        self.eksi.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.eksi.setFont(font)
        self.eksi.setObjectName("eksi")
        self.yuzde = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("%"))
        self.yuzde.setEnabled(True)
        self.yuzde.setGeometry(QtCore.QRect(34, 200, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yuzde.sizePolicy().hasHeightForWidth())
        self.yuzde.setSizePolicy(sizePolicy)
        self.yuzde.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yuzde.setFont(font)
        self.yuzde.setObjectName("yuzde")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 341, 135))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputLabel.sizePolicy().hasHeightForWidth())
        self.outputLabel.setSizePolicy(sizePolicy)
        self.outputLabel.setMaximumSize(QtCore.QSize(361, 588))
        self.outputLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outputLabel.setLineWidth(2)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def press_it(self, pressed):
        if pressed == "C":
            self.outputLabel.setText("0")
        else:
            self.outputLabel.setText(f'{self.outputLabel.text()}{pressed}')


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hesap Makinesi 1.0"))
        self.arti.setText(_translate("MainWindow", "+"))
        self.carpi.setText(_translate("MainWindow", "x"))
        self.yedi.setText(_translate("MainWindow", "7"))
        self.dokuz.setText(_translate("MainWindow", "9"))
        self.bolu.setText(_translate("MainWindow", "/"))
        self.sil.setText(_translate("MainWindow", "<<"))
        self.dort.setText(_translate("MainWindow", "4"))
        self.bir.setText(_translate("MainWindow", "1"))
        self.alti.setText(_translate("MainWindow", "6"))
        self.uc.setText(_translate("MainWindow", "3"))
        self.sekiz.setText(_translate("MainWindow", "8"))
        self.bes.setText(_translate("MainWindow", "5"))
        self.iki.setText(_translate("MainWindow", "2"))
        self.sifirla.setText(_translate("MainWindow", "C"))
        self.eksi.setText(_translate("MainWindow", "-"))
        self.yuzde.setText(_translate("MainWindow", "%"))
        self.outputLabel.setText(_translate("MainWindow", "TextLabel"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())