from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.setWindowModality(QtCore.Qt.NonModal)
        WizardPage.resize(361, 588)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WizardPage.sizePolicy().hasHeightForWidth())
        WizardPage.setSizePolicy(sizePolicy)
        WizardPage.setMinimumSize(QtCore.QSize(361, 588))
        WizardPage.setMaximumSize(QtCore.QSize(361, 588))
        WizardPage.setAutoFillBackground(False)
        self.gridFrame_2 = QtWidgets.QFrame(WizardPage)
        self.gridFrame_2.setEnabled(True)
        self.gridFrame_2.setGeometry(QtCore.QRect(10, 200, 341, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.gridFrame_2.sizePolicy().hasHeightForWidth())
        self.gridFrame_2.setSizePolicy(sizePolicy)
        self.gridFrame_2.setMinimumSize(QtCore.QSize(341, 135))
        self.gridFrame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.bes = QtWidgets.QPushButton(self.gridFrame_2)
        self.bes.setGeometry(QtCore.QRect(106, 203, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bes.sizePolicy().hasHeightForWidth())
        self.bes.setSizePolicy(sizePolicy)
        self.bes.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bes.setFont(font)
        self.bes.setObjectName("bes")
        self.bir = QtWidgets.QPushButton(self.gridFrame_2)
        self.bir.setGeometry(QtCore.QRect(30, 283, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bir.sizePolicy().hasHeightForWidth())
        self.bir.setSizePolicy(sizePolicy)
        self.bir.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bir.setFont(font)
        self.bir.setObjectName("bir")
        self.dokuz = QtWidgets.QPushButton(self.gridFrame_2)
        self.dokuz.setGeometry(QtCore.QRect(182, 123, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dokuz.sizePolicy().hasHeightForWidth())
        self.dokuz.setSizePolicy(sizePolicy)
        self.dokuz.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dokuz.setFont(font)
        self.dokuz.setObjectName("dokuz")
        self.sifirla = QtWidgets.QPushButton(self.gridFrame_2)
        self.sifirla.setGeometry(QtCore.QRect(106, 43, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sifirla.sizePolicy().hasHeightForWidth())
        self.sifirla.setSizePolicy(sizePolicy)
        self.sifirla.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sifirla.setFont(font)
        self.sifirla.setObjectName("sifirla")
        self.uc = QtWidgets.QPushButton(self.gridFrame_2)
        self.uc.setGeometry(QtCore.QRect(182, 283, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uc.sizePolicy().hasHeightForWidth())
        self.uc.setSizePolicy(sizePolicy)
        self.uc.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.uc.setFont(font)
        self.uc.setObjectName("uc")
        self.bolu = QtWidgets.QPushButton(self.gridFrame_2)
        self.bolu.setGeometry(QtCore.QRect(258, 43, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bolu.sizePolicy().hasHeightForWidth())
        self.bolu.setSizePolicy(sizePolicy)
        self.bolu.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bolu.setFont(font)
        self.bolu.setObjectName("bolu")
        self.sekiz = QtWidgets.QPushButton(self.gridFrame_2)
        self.sekiz.setGeometry(QtCore.QRect(106, 123, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sekiz.sizePolicy().hasHeightForWidth())
        self.sekiz.setSizePolicy(sizePolicy)
        self.sekiz.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sekiz.setFont(font)
        self.sekiz.setObjectName("sekiz")
        self.dort = QtWidgets.QPushButton(self.gridFrame_2)
        self.dort.setGeometry(QtCore.QRect(30, 203, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dort.sizePolicy().hasHeightForWidth())
        self.dort.setSizePolicy(sizePolicy)
        self.dort.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dort.setFont(font)
        self.dort.setObjectName("dort")
        self.eksi = QtWidgets.QPushButton(self.gridFrame_2)
        self.eksi.setGeometry(QtCore.QRect(258, 203, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eksi.sizePolicy().hasHeightForWidth())
        self.eksi.setSizePolicy(sizePolicy)
        self.eksi.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.eksi.setFont(font)
        self.eksi.setObjectName("eksi")
        self.yedi = QtWidgets.QPushButton(self.gridFrame_2)
        self.yedi.setGeometry(QtCore.QRect(30, 123, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yedi.sizePolicy().hasHeightForWidth())
        self.yedi.setSizePolicy(sizePolicy)
        self.yedi.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yedi.setFont(font)
        self.yedi.setObjectName("yedi")
        self.yuzde = QtWidgets.QPushButton(self.gridFrame_2)
        self.yuzde.setEnabled(True)
        self.yuzde.setGeometry(QtCore.QRect(30, 43, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yuzde.sizePolicy().hasHeightForWidth())
        self.yuzde.setSizePolicy(sizePolicy)
        self.yuzde.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yuzde.setFont(font)
        self.yuzde.setObjectName("yuzde")
        self.carpi = QtWidgets.QPushButton(self.gridFrame_2)
        self.carpi.setGeometry(QtCore.QRect(258, 123, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carpi.sizePolicy().hasHeightForWidth())
        self.carpi.setSizePolicy(sizePolicy)
        self.carpi.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.carpi.setFont(font)
        self.carpi.setObjectName("carpi")
        self.sil = QtWidgets.QPushButton(self.gridFrame_2)
        self.sil.setGeometry(QtCore.QRect(182, 43, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sil.sizePolicy().hasHeightForWidth())
        self.sil.setSizePolicy(sizePolicy)
        self.sil.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sil.setFont(font)
        self.sil.setObjectName("sil")
        self.iki = QtWidgets.QPushButton(self.gridFrame_2)
        self.iki.setGeometry(QtCore.QRect(106, 283, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iki.sizePolicy().hasHeightForWidth())
        self.iki.setSizePolicy(sizePolicy)
        self.iki.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.iki.setFont(font)
        self.iki.setObjectName("iki")
        self.alti = QtWidgets.QPushButton(self.gridFrame_2)
        self.alti.setGeometry(QtCore.QRect(182, 203, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alti.sizePolicy().hasHeightForWidth())
        self.alti.setSizePolicy(sizePolicy)
        self.alti.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.alti.setFont(font)
        self.alti.setObjectName("alti")
        self.arti = QtWidgets.QPushButton(self.gridFrame_2)
        self.arti.setGeometry(QtCore.QRect(258, 283, 50, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arti.sizePolicy().hasHeightForWidth())
        self.arti.setSizePolicy(sizePolicy)
        self.arti.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.arti.setFont(font)
        self.arti.setObjectName("arti")
        self.frame = QtWidgets.QFrame(WizardPage)
        self.frame.setGeometry(QtCore.QRect(10, 20, 361, 145))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 341, 135))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "Hesap Makinesi"))
        WizardPage.setTitle(_translate("WizardPage", "Hesap Makinesi"))
        self.bes.setText(_translate("WizardPage", "5"))
        self.bir.setText(_translate("WizardPage", "1"))
        self.dokuz.setText(_translate("WizardPage", "9"))
        self.sifirla.setText(_translate("WizardPage", "C"))
        self.uc.setText(_translate("WizardPage", "3"))
        self.bolu.setText(_translate("WizardPage", "/"))
        self.sekiz.setText(_translate("WizardPage", "8"))
        self.dort.setText(_translate("WizardPage", "4"))
        self.eksi.setText(_translate("WizardPage", "-"))
        self.yedi.setText(_translate("WizardPage", "7"))
        self.yuzde.setText(_translate("WizardPage", "%"))
        self.carpi.setText(_translate("WizardPage", "x"))
        self.sil.setText(_translate("WizardPage", "<<"))
        self.iki.setText(_translate("WizardPage", "2"))
        self.alti.setText(_translate("WizardPage", "6"))
        self.arti.setText(_translate("WizardPage", "+"))
        self.label.setText(_translate("WizardPage", "TextLabel"))
