# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HM_AraYüz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.setWindowModality(QtCore.Qt.NonModal)
        WizardPage.resize(480, 640)
        WizardPage.setAutoFillBackground(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(WizardPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lcdNumber = QtWidgets.QLCDNumber(WizardPage)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_2.addWidget(self.lcdNumber, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(WizardPage)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(WizardPage)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(WizardPage)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(WizardPage)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(WizardPage)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(WizardPage)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 2, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(WizardPage)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(WizardPage)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(WizardPage)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 0, 1, 1)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "Hesap Makinesi"))
        WizardPage.setTitle(_translate("WizardPage", "Hesap Makinesi"))
        self.pushButton.setText(_translate("WizardPage", "7"))
        self.pushButton_7.setText(_translate("WizardPage", "5"))
        self.pushButton_6.setText(_translate("WizardPage", "6"))
        self.pushButton_10.setText(_translate("WizardPage", "1"))
        self.pushButton_9.setText(_translate("WizardPage", "2"))
        self.pushButton_4.setText(_translate("WizardPage", "3"))
        self.pushButton_2.setText(_translate("WizardPage", "8"))
        self.pushButton_3.setText(_translate("WizardPage", "4"))
        self.pushButton_5.setText(_translate("WizardPage", "9"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WizardPage = QtWidgets.QWizardPage()
    ui = Ui_WizardPage()
    ui.setupUi(WizardPage)
    WizardPage.show()
    sys.exit(app.exec_())
